---
# file: roles/jenkins/tasks/main.yml


#- name: copying jenkins repository
#  action: copy src=etc/apt/jenkins-ci.org.key dest=/etc/apt/jenkins-ci.org.key force=no owner=root group=root mode=0644
#  register: jenkins_install

- name: add jenkins apt repository key
  apt_key: url="{{ jenkins.key }}" state=present
  #"
  #apt_key: file=etc/apt/jenkins-ci.org.key state=present
  #action: command apt-key add /etc/apt/jenkins-ci.org.key

- name: installing jenkins repository
  apt_repository: repo="{{ jenkins.repo }}" state=present update_cache=yes
  #"
  #apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present update_cache=yes
  #action: copy src=etc/apt/sources.list.d/jenkins.list dest=/etc/apt/sources.list.d/jenkins.list force=no owner=root group=root mode=0644

- name: installing packages - jenkins
  apt: name={{ item }}  state=present 
  register: jenkins_install
  with_items: jenkins.packages
  #- openjdk-6-jdk
  #- jenkins
  #- libjenkins-plugin-parent-java


- name: be sure services are running and enabled
  service: name={{ item }} state=started enabled=yes
  with_items:
  - jenkins

# Install Jenkins cli
- include: cli.yml
# Add credentials
- include: github-access.yml
