- name: trget setup
  hosts: "{{ target }}"
  #remote_user: ubuntu
  sudo: yes
  gather_facts: false
  tasks:
  - ping:

- name: target
  hosts: "{{ target }}"
  #remote_user: ubuntu
  sudo: yes
  gather_facts: false
  tasks:
  - ping:

# vim:ts=2 sw=2 et autoindent
