- name: server setup
  #hosts: "{{ target }}"
  hosts: all
  sudo: yes
  gather_facts: false
  roles:
  - { role: infr-common, when: "'infr-common' in roles and roles is defined" }
  - { role: jenkins, when: "'jenkins' in roles and roles is defined" }
  - { role: varnish, when: "'varnish' in roles and roles is defined" }
  - { role: sbt, when: "'sbt' in roles and roles is defined" }
  - { role: gradle, when: "'gradle' in roles and roles is defined" }
  - { role: nodejs, when: "roles.nodejs is defined" }
  #- { role: nodejs, when: "'nodejs' in roles and roles is defined" }
  - { role: host_services, when: "host_services is defined" }
  - { role: acme-server, when: "acme_server is defined", tags: [ 'timezone' ] }
# vim:ts=2 sw=2 et autoindent
