---
# This playbook installs aptly
- hosts: aptly
  user: "{{ deploy_user }}"
  sudo: False 
  gather_facts: no

  roles:
   - aptly


#  tasks:
#   - debug: msg="hola"
#    # Add aptly repository
#    - name: Add aptly repository
#      apt_repository: repo="{{ aptly.repo }}" state=present

# #   - name: "Add aptly repository"
# #     command: gpg --keyserver keys.gnupg.net --recv-keys 2A194991

# #   - name: Add aptly repository
# #     command: gpg -a --export 2A194991 | sudo apt-key add -
#    - name: Add aptly gpg key repository
#      apt_key: data="{{ lookup ('file','files/aptly-repo.key') }}" state=present

#    # "Update repositories cache and install aptly package"
#    - apt: name=aptly update_cache=yes

#    - name: create aptly repository directory exists
#      file: path={{ web_dir }}/aptly  state=directory   owner={{ deploy_user }} group={{ deploy_group }} recurse=yes

#    - name: create aptly lib directory 
#      file: path={{ lib_dir }}/aptly  state=directory  owner={{ deploy_user }} group={{ deploy_group }} recurse=yes

#    - name: create aptly conf file 
#      copy: src=files/aptly.conf dest=/etc/aptly.conf force=no
