---
#-name: release | main | disable alerts from nagios
- name: release | main | include a10 
  include: a10.yml
  when: lb_type is defined and lb_type == "a10" and pool_type == 'dynamic'

- name: release | main | include apt
  include: apt.yml
  when: pool_type == 'static' and ansible_os_family == 'Debian'

- name: release | main | include apt
  include: osx.yml
  when: pool_type == 'static' and ansible_os_family == 'Darwin'

#-name: release | main | enable alerts from nagios

