---
- name: create admin group
  action: group name={{ rls_user_group }} system=no state=present

- name: create rls user
  user: "name={{ rls_user_name }}  comment='{{ rls_user_comment }}' group={{ rls_user_group }} shell={{ rls_user_shell }} uid={{ rls_user_uid }}"

- name: setup authorized key
  authorized_key: user={{ rls_user_name }} key="{{ lookup('file', rls_ssh_publickey_filename) }}"

- name: write the sudoers file
  template: src=admin_sudoers.j2 dest=/etc/sudoers.d/{{ rls_user_group }} owner=root group=root mode=0400

