---
- name: delete ubuntu user account
  user: name={{ item }} state=absent remove=yes
  with_items:
    - ubuntu
  tags: cleanup

- name: install python-apt required by apt module
  command: sudo apt-get -y install python-apt
