---
- name: artifact - set filename for non zipped artifact
  set_fact: filename={{ component_artifact_filename }}
  when: component_artifact_is_singlefile

- name: artifact - download artifact zipped file
  get_url: url=http://{{ jfrog_admin_user }}:{{ jfrog_admin_password }}@{{ jfrog_url }}/{{ component_input_uri }}/{{ component_artifact_filename }} dest={{ pkg_tmp_dir }}/{{ component }}/ mode=0440
  when: not component_artifact_is_singlefile

- name: artifact - unzip artifact
  command: unzip -d {{ pkg_tmp_dir }}/{{ component }}/src{{ base_prefix }}/{{ component_deploy_dir }} {{ pkg_tmp_dir }}/{{ component }}/{{ component_artifact_filename }}
  when: not component_artifact_is_singlefile

- name: artifact - nasty hack for smaug
  shell: mv src{{ base_prefix }}/{{ component_deploy_dir }}/{{ component }}-{{ version }}/* src{{ base_prefix }}/{{ component_deploy_dir }}/ chdir={{ pkg_tmp_dir }}/{{ component }}/
  when: not component_artifact_is_singlefile and component == 'smaug'

- name: artifact - download artifact single file
  get_url: url=http://{{ jfrog_admin_user }}:{{ jfrog_admin_password }}@{{ jfrog_url }}/{{ component_input_uri }}/{{ component_artifact_filename }} dest={{ pkg_tmp_dir }}/{{ component }}/src{{ base_prefix }}/{{ component_deploy_dir }} mode=0440
  when: component_artifact_is_singlefile
