---

#- fail: msg="Bailing out - this play is missing an input variable"
#  when: "{{ item }} is not defined"
#  with_items: packaging.input_vars

#- include: setup-git.yml
#  tags: setup
# - debug: var=output_type

# - debug: msg="including deb.yml"
#   when: "'deb' in output_type"

# - fail: msg="corta con tanta dulzura"


- name: main - delete directory to start clean
  file: path={{ pkg_tmp_dir }}/{{ component }} state=absent

- name: main - create directories
  file: path={{ pkg_tmp_dir }}/{{ component }}/src{{ base_prefix }}/{{ component_deploy_dir }} state=directory

- include: git.yml
  when: input_type == 'git'

- include: svn.yml
  when: input_type == 'svn'

- include: artifact.yml
  when: input_type == 'artifact'

- include: pkg-scripts.yml
  when: pkg_scripts_setup

- include: pkg-conffiles.yml
  when: pkg_conffiles_setup

- include: deb.yml
  when: output_type == 'deb'
