---
# System V /etc/init.d scripts

- name: conffiles - checking for init.d script
  stat: path={{ init_scripts_rootdir }}/{{ component }}/initd
  register: initd

- name: conffiles - create init.d directory
  file: path={{ pkg_tmp_dir }}/{{ component }}/src{{ pkg_conffiles_etcdir }}/init.d state=directory
  when: initd.stat.exists

- name: conffiles - copy init.d file
  command: cp {{ init_scripts_rootdir }}/{{ component }}/initd {{ pkg_tmp_dir }}/{{ component }}/src/{{ pkg_conffiles_etcdir }}/init.d/{{ component }}
  when: initd.stat.exists

- name: conffiles - set fpm init.d conffiles opts
  set_fact: pkg_conffiles_opts=" --config-files {{ pkg_conffiles_etcdir }}/init.d/{{ component }} "
  #"
  when: initd.stat.exists

# Upstart /etc/init scripts

- name: conffiles - checking for init script
  stat: path={{ init_scripts_rootdir }}/{{ component }}/init
  register: init

- name: conffiles - create init directory
  file: path={{ pkg_tmp_dir }}/{{ component }}/src{{ pkg_conffiles_etcdir }}/init state=directory
  when: init.stat.exists

- name: conffiles - copy init file
  command: cp {{ init_scripts_rootdir }}/{{ component }}/initd {{ pkg_tmp_dir }}/{{ component }}/src/{{ pkg_conffiles_etcdir }}/init/{{ component }}.conf
  when: init.stat.exists

- name: conffiles - set fpm init conffiles opts
  set_fact: pkg_conffiles_opts=" --config-files {{ pkg_conffiles_etcdir }}/init/{{ component }}.conf "
  #"
  when: init.stat.exists and not initd.stat.exists

- name: conffiles - set fpm init conffiles opts
  set_fact: pkg_conffiles_opts=" {{ pkg_conffiles_opts }} --config-files {{ pkg_conffiles_etcdir }}/init/{{ component }}.conf "
  #"
  when: init.stat.exists and initd.stat.exists
