---
# Debian/Ubuntu section

## first check which scripts are available
- name: pkg-scripts - checking for preinst script
  stat: path={{ init_scripts_rootdir }}/{{ component }}/preinst.sh
  register: preinst

- name: pkg-scripts - checking for postrm script
  stat: path={{ init_scripts_rootdir }}/{{ component }}/postrm.sh
  register: postrm

- name: pkg-scripts - checking for prerm script
  stat: path={{ init_scripts_rootdir }}/{{ component }}/prerm.sh
  register: prerm

- name: pkg-scripts - checking for postinst script
  stat: path={{ init_scripts_rootdir }}/{{ component }}/postinst.sh
  register: postinst

## automatically add the available scripts for deb packages

- name: pkg-scripts - set fpm postrm script opts
  set_fact: pkg_script_opts=" {{ pkg_script_opts }} {{ pkg_script_files_opt.postrm }} {{ init_scripts_rootdir }}/{{ component }}/postrm.sh"
  when: "postrm.stat.exists and 'deb' in output_type"

- name: pkg-scripts - set fpm prerm script opts
  set_fact: pkg_script_opts="{{ pkg_script_opts }} {{ pkg_script_files_opt.prerm }} {{ init_scripts_rootdir }}/{{ component }}/prerm.sh "
  when: "prerm.stat.exists and 'deb' in output_type"

- name: pkg-scripts - set fpm postinst script opts
  set_fact: pkg_script_opts="{{ pkg_script_opts }} {{ pkg_script_files_opt.postinst }} {{ init_scripts_rootdir }}/{{ component }}/postinst.sh "
  when: "postinst.stat.exists and 'deb' in output_type"

- name: pkg-scripts - set fpm preinst script opts
  set_fact: pkg_script_opts="{{ pkg_script_opts }} {{ pkg_script_files_opt.preinst }} {{ init_scripts_rootdir }}/{{ component }}/preinst.sh "
  when: "preinst.stat.exists and 'deb' in output_type"

# RPM Section
## to be done ...
