---

- name: check host status in puppet cert list
  shell: puppet cert list --all 
  sudo: yes
  register: certlist
  tags: setup
  delegate_to: localhost

- name: install puppet agent
  include: agent.yml
  when: inventory_hostname not in certlist.stdout
  tags: setup

- name: check cert sign status in puppet cert list
  shell: 'puppet cert list --all | egrep "^\+"'
  sudo: yes
  register: certsignedlist
  delegate_to: localhost
  tags: setup

- name: sign puppet agent certificate
  include: sign.yml
  when: inventory_hostname not in certsignedlist.stdout
  tags: setup

- name: puppet agent first run
  command: puppet agent --verbose --no-daemonize creates=/var/lib/puppet/state/last_run_summary.yaml
  register: agentlog
  tags: setup
#- debug: var=agentlog  

- name: cleanup tasks
  include: cleanup.yml
  tags: cleanup
