---
- name: create containers
  command: lxc-clone -o {{ lxc_clone_container }} -n  {{ item.name }} creates=/var/lib/lxc/{{ item.name }} 
  #-L 50G
  with_items: containers

- name: get running containers
  #shell: 'netstat -lx | grep lxc | cut -d\/ -f5'
  command: lxc-ls --running
  changed_when: False
  register: running_containers

- name: set default template filename var
  set_fact: template_file=config.j2

- name: set template filename var
  set_fact: template_file={{ env_name }}.config.j2
  when: env_name is defined

- name: set container networking config file
  template: src={{ template_file }} dest={{ lxc_varlib_dir }}/{{ item.name}}/config backup=yes
  with_items: containers

- name: set container to autostart
  file: >
    src={{ lxc_varlib_dir }}/{{ item.name}}/config 
    dest={{ lxc_etc_auto_dir }}/{{ item.name }}.conf
    state=link
  with_items: containers
  when: "item.status == 'auto'"

- name: start new containers
  command: lxc-start -n {{ item.name }} -d
  when: "item.name not in running_containers.stdout"
  with_items: containers

- name: get all containers
  command: lxc-ls 
  changed_when: False
  when: auto_removal is defined and auto_removal and containers_trash is defined
  register: all_containers

- name: delete no longer used containers
  command: lxc-destroy -n {{ item.name }} 
  with_items: containers_trash
  when: item != lxc_clone_container and containers_trash is defined and auto_removal is defined and auto_removal
