---
- name: setup directories
  include: directories.yml
  when: symlink_lxc_lib_dir is defined
  tags: lxc

- name: install lxc
  apt: name={{ item }}
  with_items:
    - lxc
  tags:  lxc

- name: checking for clone template
  shell: 'lxc-ls -1 | egrep "^{{ lxc_clone_template }}$"'
  ignore_errors: True
  changed_when: False
  register: lxclone
  tags:  lxc

- name: create clone template
  include: template.yml
  when: lxclone.rc
  tags: lxc

- name: create containers
  include: containers.yml
  when: containers is defined
  #when: lxclone.rc
  tags: lxc

- name: setup ssh config
  include: ssh.yml
  when: containers is defined and rls_user_name is defined
  tags: 
    - lxc
    - lxcssh
