- hosts: "{{ component }}"
  gather_facts: False
  sudo: no

  pre_tasks:

  # INCLUDES SECTION

  # input

  # extracts the component name up to the first dash
  - name: get common component filename
    set_fact: common_component="{{ component | regex_replace('(.*?)\-.*$', '\\1') }}"
  #" include common if it exists, just continue if not
  - name: include component common vars file 
    include_vars: "group_vars/common-{{ common_component }}"
    ignore_errors: yes

  # always - explicit since we are using same hostname for groups - overriding common if required
  - name: include component vars file 
    include_vars: "group_vars/{{ component }}"

  - name: main - set base_prefix
    #set_fact: base_prefix=pkg.{{ output_type }}.base_prefix # manually for now
    set_fact: base_prefix={{ pkg.deb.base_prefix }}

  - name: include component input vars file 
    include_vars: "group_vars/input-{{ component_input }}"
    when: component_input is defined
    ignore_errors: yes

  # output
  - name: include component input vars file 
    include_vars: "group_vars/output-{{ component_output }}"
    when: component_output is defined
    ignore_errors: yes



  roles:
  - packaging


  tasks:

  #- command: apt-get update -o Dir::Etc::sourcelist="sources.list.d/acme-rls.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  #  delegate_to: localhost
  #  sudo: yes
