---
- name: nms servers playbook
  hosts: all
  gather_facts: false
  vars:
    - user: vagrant
    - group: nogroup
    - homedir: /home/vagrant
  tasks:
  #- apt: name=apache2 state=present
  - name: install packages
    apt: name={{ item }}
    with_items:
     - haproxy
     - screen

  - name: copy config file
    action: copy src=files/etc/haproxy/haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
    notify:
      - restart haproxy

  - name: Sets default starting flag to 1
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify:
      - restart haproxy

  - name: start service
    service: name=haproxy state=started enabled=yes

  handlers:
  - name: restart haproxy
    service: name=haproxy state=restarted
