---

- name: installing packages
  apt: name={{ item }} state=present
  with_items:
   - zip
   - wget
   - curl
   - mc
   - screen
#  - git
#  - php-apc
#  - php5-cli
#  - php5-curl
#  - phpunit
#  - php5-memcache
